runtime: python310
automatic_scaling:
  target_cpu_utilization: 0.90
  max_instances: 1
entrypoint: gunicorn -b :$PORT app:server
env_variables:
  BUCKET_NAME_1: 'pm25_correlation_data'
  BUCKET_NAME_2: 'fresno_daily_data'